version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4593:4567-4593"
    environment:
      - SERVICES=s3,firehose,kinesis,iam
      - START_WEB=0
      - FORCE_NONINTERACTIVE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
